### ISSUE TITLE
a11y support

### ISSUE THREAD

**Issue by marlonmarcello** [wethegit/wtc-perspective-card#4]
**Issue**
The animation autoplays and it contains a lot of movement.

**Solution**
We should change the behaviour of the animation to be option based and also to check for `prefers-reduce-motion`.

**Comment by liamegan** [comment]
I'm assigning this one to @andrewrubin for the V2 build.

**Comment by marlonmarcello** [comment]
@andrewrubin to give you an update.
On v2, the ambient effect is under a variable/setting called `ambient`.
So it's already a step towards better a11y support. We now just need to make sure that when `ambient` is **ON** it automatically turns itself **OFF** when reduce motion is enabled.

**Comment by andrewrubin** [comment]
@marlonmarcello @liamegan This sounds like it may be getting a little too closely coupled with our “proprietary” reduce motion functionality. Are we okay with relying on our WTC reduce motion standard for this (the specific localStorage variable we use)? I ask, because prefers-reduced-motion by itself is still not widely supported. 

I’m thinking that this specific functionality should be handled outside the component, so it’s not so opinionated about reduce motion specifically. For example, we could use our usual event listener for when RM Changes, and then, using an interface provided by this component, toggle on/off the ambient variable you mentioned. In other words, remove reduce motion from the equation, and let the developer decide how best to toggle ambient animation for the situation in question.

I get that we will probably be the only ones to ever use this component, so using our specific RM variables inside the component is probably fine… but I’m just thinking with regard to open-sourcing it in the future. What do you guys think? Does that make sense?

**Comment by andrewrubin** [comment]
I had this big old comment written out about how we should decouple our RM logic from our components, but I literally just checked the support for `prefers-reduced-motion` and it's pretty good 🙃

So I was thinking, inside the component, I will make some custom event that fires when `match media` detects a `prefers-reduced-motion` toggle. This is because if we _only_ toggle RM on/off, the Observer callback won't fire again until you scroll around a bit. Sound good?

**Comment by liamegan** [comment]
So after thinking on this, I have opinions.

On all sites where we implement RM we have a component that's resposible for toggling the functionality and doing so in the presence of `prefers-reduced-motion`, making this determination within components like this one either redundant (at best) or problematic (at worst).

This class already has a `playing` get/set that we can very easily use to turn motion on or off. Is there any real benefit in introducing a bunch of code to turn off motion in various sections in the presence of the already more robust RM triggers that we already use?

**Comment by marlonmarcello** [comment]
I hear you guys.

In my head, the class itself should be responsible for turning itself on/off, if the user `prefers-reduce-motion` than the animation should not play period.

In my head that statement is a must and relying on the developer to take care of it is putting too much trust on him.

But... I also understand completely what you guys are saying. It's one extra dependency, extra code and stuff that could be lifted to a global class on the project.
I also think that our proprietary reduce motion follows the standard pretty well.

With all that in mind, I think you guys make a better point. It's not expected for a class to respond to `reduce-motion` natively, even tho that is nice, it's extra stuff indeed and can be easily integrated with out bootstrap, so, closing.

Thank you!
